### ISSUE TITLE
adjustable volume size option needed

### ISSUE THREAD

**Issue by trodemaster** [ninxsoft/mist-cli#102]
Looks like the latest installer for macos 13.0 is bigger than the volume created by mist-cli. I would be nice to have a flag that lets you adjust that size for situations like this. I'm running mist 1.8 on x86_64 macOS  12.5, attempting to make an iso of 13.0b 22A5321d

```
sudo mist download installer --include-betas 22A5321d iso --iso-name macOS_%VERSION%_%BUILD%.iso 
```
Results in the following...

```
Creating new temporary directory '/Users/blake/code/packer-macOS-11/install_bits/012-51393/iso'...
  ├─ Creating disk image '/Users/blake/code/packer-macOS-11/install_bits/012-51393/iso/012-51393.dmg'...
  ├─ Mounting disk image at mount point '/Volumes/Install macOS Ventura beta'...
  ├─ Creating install media at mount point '/Volumes/Install macOS Ventura beta'...
  └─ Invalid Exit Status Code: '246', Message: /Volumes/Install macOS Ventura beta is not large enough for install media. An additional 182.3 MB is needed.

Error: invalidExitStatus(code: 246, message: "/Volumes/Install macOS Ventura beta is not large enough for install media. An additional 182.3 MB is needed.\n")
```

**Comment by ninxsoft** [comment]
Ah dang, I missed by 182.3 MB!

My current "naive" logic is to round up total download size to the nearest gigabyte, and add 1 GB.

I am tempted to cheat short-term and just add a tiny bit to the dmg size, and maybe circle back with an option to specify an ISO size.

Thanks for the heads up!

**Comment by ninxsoft** [comment]
Here's my quick and dirty fix (adds 500MB): https://github.com/ninxsoft/mist-cli/commit/149db497495c076c8508832d7b3cafb61145413e

**Comment by trodemaster** [comment]
Was able to build the branch with this workaround and can confirm it works with the latest ventura beta.

**Comment by iresh-filewave** [comment]
@trodemaster Thanks for pointing here. This change is not the part of latest release ? I have tried to build `mist-macOS installer` using Xcode and got error regarding package `Sparkle`

```
dyld[9050]: Library not loaded: '@rpath/Sparkle.framework/Versions/B/Sparkle'
  Referenced from: '/Users/id/Library/Developer/Xcode/DerivedData/Mist-drovaghzlwgtrmdjxynnrlzvmtfm/Build/Products/Debug/Mist.app/Contents/MacOS/Mist'
```

**Comment by ninxsoft** [comment]
The change has been committed to the repo but a new release has not been created. A new release will be made available today.

Thanks for your patience @iresh-filewave! 🙌
