### ISSUE TITLE
brew 1.9.1 failing to build

### ISSUE THREAD

**Issue by NorseGaud** [ninxsoft/mist-cli#108]
See https://github.com/Homebrew/homebrew-core/pull/112622/files for the errors while building

```
==> Downloading https://github.com/ninxsoft/mist-cli/releases/download/v1.9.1/mist-cli.1.9.1.pkg
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/13955ba435543ba9401a080db58c515ddbeab1469a7ae76059a4226e43c1790d--mist-cli.1.9.1.pkg
==> Verifying checksum for '13955ba435543ba9401a080db58c515ddbeab1469a7ae76059a4226e43c1790d--mist-cli.1.9.1.pkg'
cp -p /Users/brew/Library/Caches/Homebrew/downloads/13955ba435543ba9401a080db58c515ddbeab1469a7ae76059a4226e43c1790d--mist-cli.1.9.1.pkg /private/tmp/mist-20221008-71614-1jba5vr/mist-cli.1.9.1.pkg
==> swift build --disable-sandbox --configuration release
error: Could not find Package.swift in this directory or any of its parent directories.
```

**Comment by ninxsoft** [comment]
Having a quick look at the pull request you created, it appears the url you are targeting is the package containing the compiled binary, and not the compressed tar containing the source that homebrew would use to build the binary.

Try pointing to `https://github.com/ninxsoft/mist-cli/archive/refs/tags/v1.9.1.tar.gz` and try again?

**Comment by NorseGaud** [comment]
Ah...the brew system chose that automatically... guess it needs to be updated in their files

**Comment by NorseGaud** [comment]
I'll wait for the next release and try it again.

**Comment by ninxsoft** [comment]
Looks like we're in business: https://github.com/Homebrew/homebrew-core/pull/112622
