### ISSUE TITLE
proposal for consistent release pkg names

### ISSUE THREAD

**Issue by NorseGaud** [ninxsoft/mist-cli#109]
Hey! I'd like to propose that pkg releases follow a pattern that doesn't change between releases. I see that 1.8 had `Mist.1.8.pkg`, yet 1.9.1 has `mist-cli.1.9.1.pkg`. I like the `mist-cli.{VERSION}.pkg` format a lot and would love for that to be the standard so I can easily automate changing the download URL when new versions of mist are released.

Thanks!

**Comment by ninxsoft** [comment]
Sunds great!

Version **1.8** > **1.9** of mist-cli was around the time [Mist.app](https://github.com/ninxsoft/Mist) was released, so the change in release names was established to minimise confusion.

Moving forward, mist-cli will continue to follow the `mist-cli.{VERSION}.pkg` filename format 👍
