### ISSUE TITLE
An idea not an issue: package option

### ISSUE THREAD

**Issue by grahampugh** [ninxsoft/mist-cli#111]
Hey Nindi, I'm finally getting around to switching my erase-install script to use mist, at least on macOS 11+, thanks to the compatibility stuff you added a few months back. So I've been trying a few things out.

One thing I noticed and didn't expect is that with the `package` option, you still download the whole app and then wrap it inside a new package with a postinstall. I wondered if you'd looked at just grabbing the `InstallAssistant.pkg` directly and renaming it? In my tests (and Armin Briegel too), this package installs the `Install macOS XY.app` perfectly well. It would save a whole lot of time with the post-download package build, and avoids touching `/Applications` at all.

**Comment by ninxsoft** [comment]
Hi @grahampugh, that sounds like a great idea!

If I recall correctly, I was trying to avoid split logic for macOS 10.x and  macOS 11+.

If the end result saves time for the user (and for myself during testing heh), I am all for it 👍

**Comment by grahampugh** [comment]
That is true, it's only relevant for macOS 11+. Hopefully that's becoming less of an issue now that 10.15 is EOL.

**Comment by ninxsoft** [comment]
#115 removes a significant amount of custom code + `mist` runs quicker when you only need to export macOS 11+ packages (and not DMG / ISO etc.).

Chef's kiss for this feature add @grahampugh 🤌
