### ISSUE TITLE
`Invalid Exit Status Code: '9', Message:` on M1

### ISSUE THREAD

**Issue by KenjiTakahashi** [ninxsoft/mist-cli#121]
Trying to build iso on an M1 MacBook fails with the following result:
```bash
┌─────────────────────┐
│ BOOTABLE DISK IMAGE │
└─────────────────────┘
  ├─ Creating new temporary directory '/private/tmp/com.ninxsoft.mist/061-26589/iso'...
  ├─ Creating disk image '/private/tmp/com.ninxsoft.mist/061-26589/iso/061-26589.dmg'...
  ├─ Mounting disk image at mount point '/Volumes/Install macOS Mojave'...
  ├─ Creating install media at mount point '/Volumes/Install macOS Mojave'...
  └─ Invalid Exit Status Code: '9', Message:
```

For what it's worth, looks like others also have the problem: https://github.com/BITespresso/createinstalliso/issues/2.

**Comment by ninxsoft** [comment]
Slightly less buried in [Mist.app](https://github.com/ninxsoft/Mist):

![Screenshot 2023-01-24 at 7 19 58 pm](https://user-images.githubusercontent.com/4812595/214242831-41c378fc-9913-43b9-8554-6915d71a7781.png)

**Comment by KenjiTakahashi** [comment]
Ah, I indeed missed that note, sorry!
Wonder if there is a way to fix it, though. I am kinda in a chicken and egg situation right now. My old Mac is dying and the only other MacOS machine I have is a new M1 MacBook. Cannot even install in a VM, because I would first have to have an installer 😅.

**Comment by ninxsoft** [comment]
Hmm good point 🤔

It might be worth bringing up your issue in the [#mist](https://macadmins.slack.com/archives/CF0CFM5B7) channel in the [Mac Admins Slack](https://macadmins.slack.com/) and see what the brains trust can conjure up 👍

**Comment by KenjiTakahashi** [comment]
So I have looked around and did some experiments. It looks indeed to be incompatible signature problem, like some suggested in other threads. There is no need to _remove_ it, though, it can be replaced with a new one.

I've made a dirty patch to `mist` like this:
[codesign.patch](https://github.com/ninxsoft/mist-cli/files/10526957/codesign.patch)

And was able to successfully create installer image for Mojave on Ventura on M1 MacBook.

Guess a more proper code would only apply this if necessary and maybe even have it behind some "at your own risk" flag.
If you're fine with that, I might have a try at creating a PR.

**Comment by ninxsoft** [comment]
I am hesitant to allow the ability to modify the contents of macOS Installers provided by Apple, even if it's just the removal of a code-signing certificate.

I can however look into a more explicit error message that blocks the user from proceeding when attempting to download  **macOS Catalina 10.15** with the `iso` option selected 👍

**Comment by ninxsoft** [comment]
@KenjiTakahashi I have added more descriptive output when attempting to build a macOS 10.15 or older ISO on an Apple Silicon Mac: #133

```bash
➜ sudo mist download installer "Mojave" iso
┌──────────────────┐
│ INPUT VALIDATION │
└──────────────────┘
  ├─ User is 'root'...
  ├─ Download search string will be 'Mojave'...
  ├─ Include betas in search results will be 'false'...
  ├─ Only include compatible installers will be 'false'...
  ├─ Cache downloads will be 'false'...
  ├─ Output directory will be '/Users/Shared/Mist'...
  ├─ Temporary directory will be '/private/tmp/com.ninxsoft.mist'...
  ├─ Force flag has not been set, existing files will not be overwritten...
  ├─ Bootable Disk Image name will be 'Install %NAME% %VERSION%-%BUILD%.iso'...
┌────────┐
│ SEARCH │
└────────┘
  ├─ Searching for macOS download 'Mojave'...
  ├─ Found [061-26589] macOS Mojave 10.14.6 (18G103) [2019-10-15]
  ├─ macOS Catalina 10.15 and older cannot generate Bootable Disk Images on Apple Silicon Macs...
  └─ Replace 'iso' with another output type or select a newer version of macOS, exiting...
```

**Comment by KenjiTakahashi** [comment]
That's fine by me. I suppose if someone really needs it, they can find this conversation and do the mod like I did. And I hope that I'll never need this again ;-).
