### ISSUE TITLE
Specified OS does not download

### ISSUE THREAD

**Issue by kylerobertson0404** [ninxsoft/mist-cli#122]
When specifying an OS that has one less decimal, mist will pull the latest version--which may be undesired.

If I search "11.7" it will pull "11.7.4"

If I search "13.2" it will pull "13.2.1"

If I try adding a ".0" (i.e. 13.2.0), it can't find the installer.

**Comment by ninxsoft** [comment]
I can confirm the same behaviour you are experiencing - nice pickup!

- `mist download firmware 13.2.1` should download **macOS Ventura 13.2.1 (22D68)**
- `mist download firmware Ventura` should download (latest) **macOS Ventura 13.2.1 (22D68)**
- `mist download firmware 13.2` should download **macOS Ventura 13.2 (22D49)**

Should be able to update the search to filter on exact matches only 👍

**Comment by ninxsoft** [comment]
This is fixed in https://github.com/ninxsoft/mist-cli/commit/c19d4e1247d3c7413fa23443b877d42fe370241e, and will make it into the next release of `mist-cli` 👍
