### ISSUE TITLE
Checking for free disk space

### ISSUE THREAD

**Issue by anewhouse** [ninxsoft/mist-cli#124]
Currently, the method Mist uses to get the amount of free disk space returns the same value as `df` or `diskutil`, which is a lower number than what's reported elsewhere in the OS.

In my testing it wouldn't download the installer on my own machine because it said I only had 34 GB free, when elsewhere macOS reported 143 GB available. Based on [Apple's documentation](https://developer.apple.com/documentation/foundation/urlresourcekey/checking_volume_storage_capacity) you might want to look into querying against volumeAvailableCapacityForImportantUsageKey - that's what Graham Pugh's erase-install.sh uses starting with version 25 and it seems to work well, although that method of running JavaScript via osascript returns 0 if no user is signed in so it falls back on df if that happens. I'm guessing you might not have that problem in Swift though!

**Comment by ninxsoft** [comment]
Thanks for bringing this to my attention - the current logic to calculate free space was hacked together quickly and can definitely be improved!

Please bear with me as I look into this and report back 🙏

**Comment by ninxsoft** [comment]
@anewhouse thanks for the suggestion, this has been implemented in #128
