### ISSUE TITLE
hdiutil attach should be using the -nobrowse option

### ISSUE THREAD

**Issue by wakco** [ninxsoft/mist-cli#125]
Line 42 of `Mist/Helpers/Installer.swift`, and Line 211 of `Mist/Helpers/Generator.swift`, inserting `"-nobrowse",` between `"-noverify",` and `"-mountpoint",` will stop the finder showing the images being mounted.

I was thinking of using this to help manage downloading of macOS installers on managed Macs, however there is no reason for end users to see volumes like `002-75541` or `Install macOS Ventura` appearing on the desktop. Could we have this option added please?

I can generate a pull request if you prefer?

**Comment by wakco** [comment]
I got the idea of using it from [atomczynski](https://macadmins.slack.com/archives/CD48Q2VRV/p1680643329799889) on MacAdmins slack in #[eraseinstall](https://macadmins.slack.com/archives/CD48Q2VRV/p1680643329799889), and after testing found mist to be more reliable than the softwareupdate command, but was disturbed by the disk images appearing on the desktop when they mounted.

**Comment by ninxsoft** [comment]
Sounds like a great idea! I can get this tested and updated in about two weeks if you're happy to wait. Alternatively, more than happy to review a pull request if you're game!

Thanks!

**Comment by wakco** [comment]
[Pull request](https://github.com/ninxsoft/mist-cli/pull/126#issue-1665524794) created, happy to wait for you to test and release it.

**Comment by ninxsoft** [comment]
Thanks for looking into this - merged in #126 👍
