### ISSUE TITLE
Invalid Exit Status Code: '1', Message

### ISSUE THREAD

**Issue by iandunton101** [ninxsoft/mist-cli#139]
### :beetle: Description

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

```bash
??????@Computername ?????? % sudo mist download installer "22F66" application --output-directory ~/Desktop
Password:
┌──────────────────┐
│ INPUT VALIDATION │
└──────────────────┘
 ├─ User is 'root'...
 ├─ Download search string will be '22F66'...
 ├─ Include betas in search results will be 'false'...
 ├─ Only include compatible installers will be 'false'...
 ├─ Cache downloads will be 'false'...
 ├─ Output directory will be '/Users/1234/Desktop'...
 ├─ Temporary directory will be '/private/tmp/com.ninxsoft.mist'...
 ├─ Force flag has not been set, existing files will not be overwritten...
 ├─ Application name will be 'Install %NAME% %VERSION%-%BUILD%.app'...
┌────────┐
│ SEARCH │
└────────┘
 ├─ Searching for macOS download '22F66'...
 ├─ Found [032-84910] macOS Ventura 13.4 (22F66) [2023-05-18]
┌───────┐
│ SETUP │
└───────┘
 ├─ Deleting old temporary directory '/private/tmp/com.ninxsoft.mist/032-84910'...
 ├─ Creating new temporary directory '/private/tmp/com.ninxsoft.mist/032-84910'...
┌──────────┐
│ DOWNLOAD │
└──────────┘
 ├─ [ 1 / 7 ] 032-84910.English.dist.......... [ 07.53 KB / 07.53 KB (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 2 / 7 ] BuildManifest.plist............. [ 06.47 MB / 06.47 MB (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 3 / 7 ] Info.plist...................... [ 05.25 KB / 05.25 KB (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 4 / 7 ] InstallAssistant.pkg............ [ 11.79 GB / 11.79 GB (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 5 / 7 ] InstallInfo.plist............... [ 0181 B / 0181 B (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 6 / 7 ] MajorOSInfo.pkg................. [ 01.33 MB / 01.33 MB (100.0%) ]
 │      Verifying... ✓✓✓
 ├─ [ 7 / 7 ] UpdateBrain.zip................. [ 03.49 MB / 03.49 MB (100.0%) ]
 │      Verifying... ✓✓✓
┌─────────┐
│ INSTALL │
└─────────┘
 ├─ Creating image '/private/tmp/com.ninxsoft.mist/032-84910/032-84910.dmg'...
 ├─ Mounting disk image at mount point '/Volumes/032-84910'...
 ├─ Creating new installer '/Volumes/032-84910//Applications/Install macOS Ventura.app'...
 └─ Invalid Exit Status Code: '1', Message:
??????@Computername ??????  %
```

### :white_check_mark: Expected Behaviour

Ventura fails to install when running erase-install

### :computer: Environment

- mist version (`mist --version`): **1.12**
- macOS Version (`sw_vers`): **20G1345**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **MacBookAir10,1**
  - Chip : **Apple M1**

### :camera: Screenshots

If applicable, add screenshots to help explain the bug.

### :information_source: Additional context

- Is this also a bug in [Mist.app](https://github.com/ninxsoft/Mist)? :white_check_mark: / :x:
  - Provide links to GitHub Issues
- Links to 3rd-party tools / references / documentation

**Comment by grahampugh** [comment]
Does `mist` have permissions to write to `~/Desktop`? Try outputting to somewhere "safe" like `/Users/Shared`.

**Comment by iandunton101** [comment]
@ninxsoft do you need any other info?

Kind regards

Ian

**Comment by ninxsoft** [comment]
@iandunton101 unfortunately the log you have provided doesn't narrow down any potential root causes. Are you able to try the following steps are report back please?

1. Does the issue persist after a reboot?
2. Can you replicate the issue on another device?
3. Are you able to try with another installer version, eg. **13.4.1** or **12.6.7**
4. Can you confirm you have granted your **Terminal** app of choice Full Disk Access via [System Settings](https://support.apple.com/en-us/guide/mac-help/mh15217/13.0/mac/13.0):

![Full Disk Access](https://github.com/ninxsoft/mist-cli/blob/main/README%20Resources/Full%20Disk%20Access.png?raw=true)

**Note:** If you specify `--cache-downloads` and `--temporary-directory /path/to/your/temp`, the downloads will be cached, saving you bandwidth and time 👍

**Comment by iandunton101** [comment]
@ninxsoft  thank you for your email

I had initially re-imaged the Mac with Big Sur, the first time I ran the erase-install process using Jamf, the Mac would not boot, I had to use Apple Configurator and revive to update the firmware. All subsequent attempts to use erase-install and Mist on it's own did not work (as above).
I have now re-imaged the Mac and erase-install / Mist are now working ok, thank you for your help
