### ISSUE TITLE
brew install does not work on Big Sur

### ISSUE THREAD

**Issue by indexofrefraction** [ninxsoft/mist-cli#143]
`brew install mist-cli`
mist-cli: A full installation of Xcode.app 14.3 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 14.3 cannot be installed on macOS 11.
You must upgrade your version of macOS.
Error: mist-cli: An unsatisfied requirement failed this build.

**Comment by ninxsoft** [comment]
This is correct, `mist-cli` requires **Swift 5.8** → **Xcode 14.3** → **macOS Ventura 13** to build correctly.

Having said that, the current Homebrew formula builds `mist-cli` from source, where it should be installing the compiled, codesigned and notarized  `mist` binary from the provided installer packages (pkg) via available [releases](https://github.com/ninxsoft/mist-cli/releases) assets.

I will look into updating the Homebrew formula, thanks for bringing this to my attention 👍

**Comment by indexofrefraction** [comment]
sorry, a bit off topic but... what is the identifier for ?
naturally i used it for an download installer command, 
but then mist doesn't find the os version.

**Comment by rodrigoseclen** [comment]
When can we expect to see Sonoma listed, also I would like to join the mac-admins slack channel

**Comment by ninxsoft** [comment]
> sorry, a bit off topic but... what is the identifier for ? naturally i used it for an download installer command, but then mist doesn't find the os version.
> 

@indexofrefraction if you are referring to the `###-#####` style identifier strings for each macOS Installer, that is the ID associated with each installer entry in the Software Update Catalog provided by Apple.

To search, you can use the macOS Installer name, version or build strings.

`mist download installer --help` for more info - look for `search-string` 👍

&nbsp;

> I would like to join the mac-admins slack channel

@rodrigoseclen I recommend visiting here to sign up: https://www.macadmins.org 👍

**Comment by ninxsoft** [comment]
I have kicked off a discussion to hopefully get some guidance / assistance:

https://github.com/orgs/Homebrew/discussions/4833

**Comment by ninxsoft** [comment]
https://github.com/orgs/Homebrew/discussions/4833#discussioncomment-7230876

As formulae are built from source by definition, I'm afraid there doesn't seem to be a path forward to provide pre-built (signed and notarized) packages for mist-cli.

Will go ahead and close this issue, will re-open if anything changes 👍
