### ISSUE TITLE
Running v1.14 on Big Sur fails after download

### ISSUE THREAD

**Issue by nabeards** [ninxsoft/mist-cli#144]
### :beetle: Description

After installing 1.14 from the releases section, I ran `mist download firmware "macOS Ventura"`. It went through the full download process, then errored out after the download completed with
```
dyld: lazy symbol binding failed: can't resolve symbol _$sScTss5NeverORszABRs_rlE17checkCancellationyyKFZ in /usr/local/bin/mist because dependent dylib @rpath/libswift_Concurrency.dylib could not be loaded
dyld: can't resolve symbol _$sScTss5NeverORszABRs_rlE17checkCancellationyyKFZ in /usr/local/bin/mist because dependent dylib @rpath/libswift_Concurrency.dylib could not be loaded
zsh: abort      mist download firmware "macOS Ventura"
```

### :white_check_mark: Expected Behaviour

It should not error out.

### :computer: Environment

- mist version (`mist --version`): 1.14
- macOS Version (`sw_vers`): 20G80 11.5.1 Big Sur
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: Macmini9,1
  - Chip : Apple M1

### :camera: Screenshots

<img width="1445" alt="screenshot" src="https://github.com/ninxsoft/mist-cli/assets/764686/298593f9-5913-4b1e-86f9-571d627cc2b1">

**Comment by ninxsoft** [comment]
The crash seems to be relating to the `Task.checkCancellation()` call when performing the shasum validation:

https://github.com/ninxsoft/mist-cli/blob/d15c9c5ec8513bb8d8e909fad4cfdb1eda92a49f/Mist/Extensions/URL%2BExtension.swift#L26-L35

I noticed you are running **macOS Big Sur 11.5.1 (20G80)** - are you able to upgrade to or test on another Mac running the latest version of macOS Big Sur? ie. **11.7.9 (20G1426)**

**Comment by nabeards** [comment]
@ninxsoft I have since upgraded my OS to Ventura so I can't verify, sorry!

**Comment by ninxsoft** [comment]
@nabeards no problem, I will go ahead and close the issue for now. We can re-open if the issue resurfaces on the latest macOS versions 👍

**Comment by nabeards** [comment]
Just as a follow-up: I did look into running Big Sur in a VM, but that's apparently not accomplished easily. Hopefully someone will eventually come along with the latest Big Sur and can verify this isn't an issue there. 🙂
