### ISSUE TITLE
Normal searches should not get information from beta seed catalogs

### ISSUE THREAD

**Issue by grahampugh** [ninxsoft/mist-cli#149]
### :bulb: Description

I wasn't sure whether to report this as a bug or a feature request, because it's really just my opinion. 

I think that most users would expect that when running `mist list installer` without `--beta`, they would only get production installers listed. This already works fine as is to exclude most beta versions, I assume because you have some logic in the code to either look at the Product Name or the BuildVersion and interpret them as betas. But Release Candidates are a different matter. These have neither a distinctive Product Name type, nor a BuildVersion that could be interpreted differently to a prod release. Nonetheless, most people would consider them as betas and would not want to push them to end users.

### :white_check_mark: Proposed solution

The only way that I can see to get this right is to only use the production catalog for a normal search, and only add the seed catalogs when the `--include-betas` option is used. 

This would make the functionality align more closely with the Mist GUI app, without having to add parameters for each seed.

### :adhesive_bandage: Alternatives Solutions + Workarounds

For erase-install I have pushed an emergency update that manually assigns only the production catalog for those people not using the `--beta` option. It required a significant bit of recoding since mist is called in three different places (list, download, check-for-newer).

### :information_source: Additional context

- Would you also like to see this implemented in [Mist.app](https://github.com/ninxsoft/Mist)?  :x: - it already is, pretty much.

**Comment by ninxsoft** [comment]
@grahampugh I **100%** agree - it makes sense to default to just the **Standard** catalog seed, where providing the `--include-betas` flag will additionally search the **Customer** / **Developer** / **Public** seeds. The `--catalog-url` option will continue to override the defaults with the provided URL.

I suspect I ended up with this logic to save time during testing etc. but as you pointed out, release candidates or production builds that have not been released are being provided to users when they probably shouldn't.

A fix is on its way, thanks! 🙌
