### ISSUE TITLE
Use previously downloaded files if a process is terminated due to low disk space

### ISSUE THREAD

**Issue by danielarrington** [ninxsoft/mist-cli#154]
### :bulb: Description
CLI should check if a previously downloaded installer/firmware is on-disk then verify and use it instead of restarting the download automatically. This could prevent an unnecessary download for a case where there is enough disk space to download the installer/firmware files but not enough to create or copy the image later in the mist process.

I believe this already done with the GUI so this would align the two methods.

### :information_source: Additional context
My Mac had ~50GB free after the first run failed while the /private/tmp/com.ninxsoft.mist/042-55586 file was still on disk.
Before running the command a second time, I cleared up about ~15GB of disk space.
![Screenshot 2023-10-18 at 1 21 04 PM](https://github.com/ninxsoft/mist-cli/assets/36854911/b6579459-f01d-4aa2-8cf2-03f767d46b1e)

**Comment by ninxsoft** [comment]
@danielarrington have you looked into the `--cache-download` flag?

This will hold onto the downloads in the temporary directory, which can also be modified by the `--temporary-directory` option.

Upon future macOS Installer downloads, `mist-cli` will look for a cache. If one isn't found, `mist-cli` proceed with the download 👍
