### ISSUE TITLE
mist-cli exits 0 when a download fails due to disk capacity

### ISSUE THREAD

**Issue by BigMacAdmin** [ninxsoft/mist-cli#156]
### :beetle: `mist-cli` exits 0 when a download fails due to disk capacity

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

1. Get a device with under 40gb free
2. run a command like `/usr/local/bin/mist download installer 23C71 image -o /Users/Shared/Mist/DMGs`
3. run `echo $?` when the command fails

### :white_check_mark: Expected Behaviour

`mist` should exit with a unique error code indicating the issue

### :computer: Environment

```
mist --version
2.0 (latest: 2.0)
```
macOS 14.2.1
MacBook Pro 16-inch, 2021 Apple M1 Pro
```
/usr/local/bin/mist download installer 23C71 image -o /Users/Shared/Mist/DMGs
┌──────────────────┐
│ INPUT VALIDATION │
└──────────────────┘
  ├─ User is 'root'...
  ├─ Download search string will be '23C71'...
  ├─ Include betas in search results will be 'false'...
  ├─ Only include compatible installers will be 'false'...
  ├─ Cache downloads will be 'false'...
  ├─ Output directory will be '/Users/Shared/Mist/DMGs'...
  ├─ Temporary directory will be '/private/tmp/com.ninxsoft.mist'...
  ├─ Force flag has not been set, existing files will not be overwritten...
  ├─ Disk Image name will be 'Install %NAME% %VERSION%-%BUILD%.dmg'...
┌────────┐
│ SEARCH │
└────────┘
  ├─ Searching for macOS download '23C71'...
  ├─ Found [052-23678] macOS Sonoma 14.2.1 (23C71) [2024-01-10]
┌───────┐
│ SETUP │
└───────┘
  ├─ Deleting old temporary directory '/private/tmp/com.ninxsoft.mist/052-23678'...
  ├─ Creating new temporary directory '/private/tmp/com.ninxsoft.mist/052-23678'...
  └─ Not enough free space on volume '/': 36.26 GB free, 40.18 GB required
root@REDACTED Mistomatic # echo $?
0
```
### :information_source: Additional context
This causes problems with my wrapper script, which looks at the exit code of the `mist` command to know whether or not the download was successful.

**Comment by ninxsoft** [comment]
Nice catch! All errors currently return an exit code of `0`

The easy workaround is to exit non-zero for all errors - not sure if it's worth creating custom exit codes for each error as I am printing out the details already.
