### ISSUE TITLE
Any option to use the command line to update mist?

### ISSUE THREAD

**Issue by mcnahum** [ninxsoft/mist-cli#174]
I'm driving mist from a shortcut to download the last version I need and it will be perfect to have an update command to automatically download and install the last version.
(yes I guess I could curl and install on command line but will do if you don't have plan for native option)

**Comment by ninxsoft** [comment]
@mcnahum this was definitely discussed in the past, however I believe we decided to leave the update mechanism to external 3rd-party tools such as [Homebrew](https://brew.sh) or [AutoPkg](https://github.com/autopkg/autopkg).

If you are using Homebrew, you can update via `brew upgrade mist-cli`
