### ISSUE TITLE
mist cli version not correct

### ISSUE THREAD

**Issue by trodemaster** [ninxsoft/mist-cli#92]
With the repo changes from mist to mist-cli the cli tool is not returning the correct latest version. Please update mist-cli to return the latest version of mist-cli instead of it's gui frend. 

```
mist version
1.8 (Latest: 0.1.1)
```

**Comment by ninxsoft** [comment]
Thanks for the creating the issue!

Fixed in https://github.com/ninxsoft/mist-cli/commit/78b95a08ebf794fb1d2a2ba35a6b4eb8f5cf0022, release coming soon!
